<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>SafeZoneMod</AssemblyName>
    <RootNamespace>SafeZoneMod</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Il2CppInterop.Common" Version="*" />
    <PackageReference Include="BepInEx.Analyzers" Version="*" PrivateAssets="all" />
    <PackageReference Include="AllOfUs.MiraAPI" Version="0.4.1" />
    <PackageReference Include="AmongUs.GameLibs.Steam" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>lib\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
